### ISSUE TITLE
500 error when sending a GPX file

### ISSUE THREAD

**Issue by HarelM** [friek/gpx2pngservice#4]
I've tried to follow the instruction and post a GPX file to the service but got a 500 error back.
It might be that the GPX file I'm using is a bit odd but it is a valid GPX file.
The following is the file:
[route.gpx.txt](https://github.com/friek/gpx2pngservice/files/7649995/route.gpx.txt)
Thanks!
I'm creating the GPX file in the following site in case it makes any difference:
https://israelhiking.osm.org.il/

**Comment by friek** [comment]
Just tested this file with my local service and it just generated the png without any errors.
Could it be that openstreetmap is unavailable from your location? Do you see any errors in the docker container?

**Comment by friek** [comment]
This is the result by the way:
![result](https://user-images.githubusercontent.com/1595338/144613709-52a93aeb-4aed-45ee-bf07-a680880e6172.png)

**Comment by HarelM** [comment]
It should be, I'll see if I can look at the container logs. But I don't see any route in this image, am I missing something?

**Comment by friek** [comment]
There is though. The 2 dots in the upper right corner is the actual route.
I believe this depends on the zoom level configured in the script. It's been ages since I touched this, so I'm not too sure about it. I'll have to look into this later on.
